my_blog/course/urls.py
from django.urls import path

from course import views

app_name = 'course'
urlpatterns = [
    path("courses/", views.CourseListView.as_view(), name="course-list"),
    path("course/add/", views.CourseCreateView.as_view(), name="course-add"),
    path("course/<int:pk>/detail/", views.CourseDetailView.as_view(), name="course-detail"),
    path("course/<int:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("course/<int:pk>/delete/", views.CourseDeleteView.as_view(), name="course-delete"),
]

my_blog/home/urls.py
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path("search/", views.search, name="search"),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path("course/", include("course.urls")),
]

my_blog/profesor/urls.py
from django.urls import path

from profesor import views

app_name = "profesor"
urlpatterns = [
    path("profesors", views.profesors, name="profesor-list"),
]

my_blog/student/urls.py
from django.urls import path

from student import views

app_name = 'student'
urlpatterns = [
    path('students', views.students, name = 'students-list')
]

my_blog/course/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=40)
    code = models.IntegerField()

    def __str__(self):
        return f'Course: {self.name} | code: {self.code}'

class Homework(models.Model):
    name = models.CharField(max_length=40)
    due_date = models.DateField()
    is_delivered = models.BooleanField()
    
    def __str__(self):
        return f"{self.name} | fecha: {self.due_date}"

my_blog/home/models.py
from django.db import models

# Create your models here.

my_blog/profesor/models.py
from django.db import models

# Create your models here.
class Profesor(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    profession = models.CharField(max_length=40)

    def __str__(self):
        return f"{self.name} {self.last_name} | email: {self.email} | profession: {self.profession}"

my_blog/student/models.py
from django.db import models

# Create your models here.

class Studen(models.Model):
    name = models.CharField(max_length = 40)
    last_name = models.CharField(max_length = 40)
    email = models.EmailField()
    
    def __str__(self):
        return f'{self.name} {self.last_name} | email: {self.email}'
    

my_blog/course/forms.py
from django import forms
from course.models import Course

class CourseForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre del curso",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "course-name",
                "placeholder": "Nombre de curso",
                "required": "True",
            }
        ),
    )
    code = forms.IntegerField(
        label="Código:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "course-code",
                "placeholder": "Código del curso",
                "required": "True",
            }
        ),
    )
    
    class Meta:
        model = Course
        fields = ["name", "code"]

my_blog/course/views.py
from django.contrib import messages

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from course.forms import CourseForm
from course.models import Course, Homework

# Guara el modelo y definimos cuantas queremos visualizar en la pagina principal
class CourseListView(ListView):
    model = Course
    paginate_by = 3
  
#  Muestra los detalles del modelo para la vista
class CourseDetailView(DetailView):
    model = Course
    fields = ["name", "code"]

# Crea un nuevo elemento
class CourseCreateView(CreateView):
    model = Course
    success_url = reverse_lazy("course:course-list")

    form_class = CourseForm
    
    def form_valid(self, form):
        """Filter to avoid duplicate courses"""
        data = form.cleaned_data
        actual_objects = Course.objects.filter(
            name=data["name"], code=data["code"]
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El curso {data['name']} - {data['code']} ya está creado",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Curso {data['name']} - {data['code']} creado exitosamente!",
            )
            return super().form_valid(form)

# Actualiza
class CourseUpdateView(UpdateView):
    model = Course
    fields = ["name", "code"]

    def get_success_url(self):
        course_id = self.kwargs["pk"]
        return reverse_lazy("course:course-detail", kwargs={"pk": course_id})

# Elimina
class CourseDeleteView(DeleteView):
    model = Course
    success_url = reverse_lazy("course:course-list")

my_blog/home/views.py
from django.shortcuts import render
from django.db.models import Q
from course.models import Course

def index(request):
    return render(
        request=request,
        context={},
        template_name= 'home/index.html',
    )

def search(request):
    search_param = request.GET["search_param"]
    print("search: ", search_param)
    context_dict = dict()
    if search_param:
        query = Q(name__contains=search_param)
        query.add(Q(code__contains=search_param), Q.OR)
        courses = Course.objects.filter(query)
        context_dict.update(
            {
                "courses": courses,
                "search_param": search_param,
            }
        )
    return render(
        request=request,
        context=context_dict,
        template_name="home/index.html",
    )

my_blog/profesor/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.

from profesor.models import Profesor

def create_profesor(request, name: str, last_name: str, email: str, profession: str):

    template = loader.get_template("template_profesor.html")

    profesor = Profesor(
        name=name, last_name=last_name, email=email, profession=profession
    )
    profesor.save()  # save into the DB

    context_dict = {"profesor": profesor}
    render = template.render(context_dict)
    return HttpResponse(render)

def profesors(request):
    profesors = Profesor.objects.all()

    context_dict = {"profesors": profesors}

    return render(
        request=request,
        context=context_dict,
        template_name="profesor/profesor_list.html")
    

my_blog/student/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from student.models import Studen

def create_student(request, name: str = 'name', last_name: str = 'last_name', email: str = 'email'):
    
    template = loader.get_template('template_studen.html')
    
    student = Studen(name = name, last_name = last_name, email = email)
    student.save()
    
    context_dict = {'student': student}
    render = template.render(context_dict)
    return HttpResponse(render)

def students(request):
    students = Studen.objects.all()
    
    context_dict = {'students': students}
    
    return render (
        request = request,
        context = context_dict,
        template_name = 'student/students_list.html'
    )

my_blog/course/templates/course/course_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Course delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ course.name }}</h1>
                    <span class="subheading">Eliminar Curso</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el Curso: {{ course.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'course:course-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/course/templates/course/course_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Course detail
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ course.name }}</h1>
                    <span class="subheading">Detalles del curso</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Código: {{ course.code }}</h3>
    <p style="text-align: center">
        <a href="{% url 'course:course-update' course.id %}">
            <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar
        </a>
        &ensp; | &ensp;
        <a href="{% url 'course:course-delete' course.id %}">
            <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar 
        </a>
    </p>
</div>
{% endblock %}

my_blog/course/templates/course/course_form.html
{% extends "home/index.html" %}
{% load static %}

<!-- ckeditor-->
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<!-- ckeditor-->

{% block my_blog_title %}
Course Create-Update
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar curso</h2>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }} <!-- ckeditor-->
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar curso" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/course/templates/course/course_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Course list
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de cursos</h1>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
        <a class="btn btn-primary" href="{% url 'course:course-add' %}">Crear nuevo Curso</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
{% for course in course_list %}
    <!-- Post preview-->
    <div class="post-preview">
        <a href="{% url 'course:course-detail' course.id %}">
            <h2 class="post-title">Este es el curso de {{ course.name }}</h2>
            <h3 class="post-subtitle">Que tiene el código: {{ course.code }}</h3>
        </a>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endfor %}

<!--Pagination-->
<div class="container p-4">
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if course_list.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ course_list.previous_page_number }}">previous</a> |
            {% endif %}

            {% if course_list.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ course_list.number }} of {{ course_list.paginator.num_pages }} |
            </span>
            {% endif %}

            {% if course_list.has_next %}
                <a href="?page={{ course_list.next_page_number }}">next</a> |
                <a href="?page={{ course_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
<!--end of Pagination-->

<!--Pagination Class Based Views-->
{% if is_paginated %}
<div class="container p-4">
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a> |
                <a href="?page={{ course_list.previous_page_number }}">previous</a> |
            {% endif %}

            {% if page_obj.paginator.num_pages > 1 %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} |
            </span>
            {% endif %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a> |
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}
<!--end of Pagination-->

{% endblock %}

my_blog/course/templates/course/homework_list.html
{% extends "home/index.html" %}
{% load static %}
{% block coderhouse_project_content %}

<header class="masthead" style="background-image: url('../../static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de Entregables</h1>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->

            {% for homework in homeworks %}
                <!-- Post preview-->
                <div class="post-preview">
                    <h2 class="post-title">Este es el entregable: {{ homework.name }}</h2>
                    <h3 class="post-subtitle">Se debe entregar en esta fecha - {{ homework.due_date }}</h3>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

my_blog/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block my_blog_title %}
                Home
            {% endblock %}
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'course:course-list' %}">Cursos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Entregables</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Estudiantes</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Profesores</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block my_blog_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('../../static/home/assets/img/home-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Clean Blog</h1>
                            <span class="subheading">A Blog Theme by Start Bootstrap</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Messages-->
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% block my_blog_content %}

                    <!-- Buscador -->
                    <h2>Buscador de cursos</h2>
                    <form action="{% url 'home:search' %}" method="GET">
                        <div>
                            <input type="text" name="search_param" id="course_code_or_name" placeholder="Buscar.."
                            {% if search_param %} value="{{ search_param }}" {% endif %}
                            >
                            <input type="submit" value="Buscar">
                            <a style="color: blue" href="{% url 'home:index' %}"><i class="fa fa-undo"></i></a>
                        </div>
                    </form>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <!-- Si hay resultados en el buscador los presenta -->
                    {% if courses %}
                    {% for course in courses %}
                        <!-- Post preview-->
                        <div class="post-preview">
                            <h2 class="post-title">Este es el curso de {{ course.name }}</h2>
                            <h3 class="post-subtitle">Que tiene el código: {{ course.code }}</h3>
                            <p class="post-meta">
                                Creado por
                                <a href="#!">Start Bootstrap</a> 
                                en {{ course.created_at }}
                            </p>
                        </div>
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endfor %}
                    {% endif %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>

my_blog/profesor/templates/profesor/profesor_list.html
{% extends "home/index.html" %}
{% load static %}
{% block coderhouse_project_content %}

<header class="masthead" style="background-image: url('../../static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de Profesores</h1>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->

            {% for profesor in profesors %}
                <!-- Post preview-->
                <div class="post-preview">
                    <h2 class="post-title">Este es el Profesor: {{ profesor.name }}  {{ profesor.last_name }}</h2>
                    <h3 class="post-subtitle">Este es su email: - {{ profesor.email }}</h3>
                    <h3 class="post-subtitle">Esta es su profesión: - {{ profesor.profession }}</h3>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}

my_blog/student/templates/student/students_list.html
{% extends "home/index.html" %}
{% load static %}
{% block coderhouse_project_content %}

<header class="masthead" style="background-image: url('../../static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de Estudiantes</h1>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content-->
<div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->

            {% for student in students %}
                <!-- Post preview-->
                <div class="post-preview">
                    <h2 class="post-title">Este es el Profesor: {{ student.name }}  {{ profestudentsor.last_name }}</h2>
                    <h3 class="post-subtitle">Este es su email: - {{ student.email }}</h3>
                </div>
                <!-- Divider-->
                <hr class="my-4" />
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}